services:
  postgres:
    image: postgres:16
    container_name: secure-file-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securefiles

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: secure-file-api
    restart: always
    env_file:
    - .env

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/securefiles
      SECRET_KEY: ${SECRET_KEY}

    volumes:
      - uploads_data:/app/uploads   # <-- TOTO JE KĽÚČ

volumes:
  postgres_data:
  uploads_data: